### ISSUE TITLE
Demo 报异常

### ISSUE THREAD

**Issue by wang9090980** [hehonghui/android_my_pull_refresh_view#2]
setSwipeRefreshListView() 这个方法在demo里面报空指针异常。

java.lang.NullPointerException
at com.uit.pullrefresh.swipe.RefreshLvLayout.setLoading(RefreshLvLayout.java:91)

**Comment by zippozeng** [comment]
这个是因为mListViewFooter为null了，初始化方法没有调用，还是做一下非空判断的比较好

**Comment by always2tate** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setDrawingCacheBackgroundColor(int)' on a null object reference at android.widget.AbsListView.obtainView(AbsListView.java:2360)
